### ISSUE TITLE
fastQTL no longer normalizes the phenotypes

### ISSUE THREAD

**Issue by aarbduarte** [francois-a/fastqtl#11]
Hello, I've seen that you removed the option to normalize the phenotypes as was doable by using --normal flag. Was it for a particular motive? Is there any work around? Thank you in advance.

**Comment by francois-a** [comment]
Hi — No, that option is still there: `bin/fastQTL.static --help`

**Comment by aarbduarte** [comment]
additionally when running on nominal pass it finishes alright but when doing permutation it throws an error: 
![image](https://user-images.githubusercontent.com/41544311/75999265-e203f800-5ef9-11ea-9a27-82133b9c35d5.png)

**Comment by francois-a** [comment]
Can you please run the command (at the bottom) that is throwing the error?

**Comment by aarbduarte** [comment]
![image](https://user-images.githubusercontent.com/41544311/76002354-66f11080-5efe-11ea-97e7-cb9adb96e1a5.png)

**Comment by francois-a** [comment]
I meant the command that starts with /home/.../fastQTL

**Comment by aarbduarte** [comment]
```
Processing gene [AFE_1_+_43531090_43528756_43538198_Hypothetical]
  * Number of variants in cis = 780
  * Best correlation = 0.2902
  * Number of permutations = 1000 / 1203
gsl: beta.c:44: ERROR: domain error
Default GSL error handler invoked.
Aborted (core dumped)
```

**Comment by francois-a** [comment]
That error usually arises when the phenotype lacks complexity (0 or same value in most samples). I'm no longer making changes to fastQTL, but you can either try filtering out such phenotypes, or using [tensorQTL](https://github.com/broadinstitute/tensorqtl), which should be more robust to this.

**Comment by aarbduarte** [comment]
thank you for your help!
