### ISSUE TITLE
If the number of genotype samples is greater than the phenotype, will genotype samples be used to calculate MAF independently?

### ISSUE THREAD

**Issue by boiscat** [francois-a/fastqtl#12]
Hi，
I get a series of data containing ~80 genotype sample, however ~20 phenotype.  I wonder if it is possible to use 80 genotype samples instead of 20 genotype samples to calculate MAF by fastQTL?

**Comment by francois-a** [comment]
No, fastQTL will compute in-sample frequencies only (determined by the samples in the phenotype file). You can use other tools to compute MAF across all samples in the VCF.

**Comment by boiscat** [comment]
Thanks for your kind reply.

**Comment by boiscat** [comment]
Hi,
I have a new question about MAF. Would you mind briefly explaining how to calculate MAF just through dosage？（The public data I obtained just provide DS format with no vcf header）

**Comment by francois-a** [comment]
In such cases, rounded dosages are used. You can see the details of the calculation [here](https://github.com/francois-a/fastqtl/blob/master/src/readGenotypes.cpp#L130).

**Comment by boiscat** [comment]
Thanks you francois-a. ^_^~
