### ISSUE TITLE
Full column names of fastqtl permutation result.

### ISSUE THREAD

**Issue by boiscat** [francois-a/fastqtl#13]
Hi,
I am confused about the column names of FastQTL result. The introduction of FastQTL (2015) provides 11 columns but the result contains 17 columns. These unknown columns may be important to my downstream analysis. Do you mind providing complete column names?

1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
PRDM2 | 129 | 1.042640 | 30.89580 | 11.6750 | 3.62995e-05 | rs2281168 | -22037 | 11 | 12 | 0.3157890 | -1 | 0.116541 | 0.815339 | 0.305742 | 0.00199800 | 0.00082410
CTNNBIP1 | 121 | 1.109870 | 29.46320 | 12.3000 | 1.34224e-04 | rs946273 | -1997 | 6 | 6 | 0.1578950 | -1 | 0.158851 | 1.564370 | 0.711198 | 0.00199800 | 0.00204789
EMC1 | 111 | 0.999246 | 16.14040 | 12.1250 | 2.82725e-04 | rs7517930 | -14411 | 9 | 10 | 0.2631580 | 1 | 0.177539 | 0.766025 | 0.374618 | 0.00199800 | 0.00457345
ARHGEF10L | 203 | 0.994054 | 26.04640 | 12.5250 | 3.28192e-04 | rs7518251 | 7210 | 8 | 9 | 0.2368420 | -1 | 0.189843 | -1.373830 | 0.702916 | 0.00899101 | 0.00877872
PAFAH2 | 131 | 1.080160 | 15.71970 | 11.5375 | 1.04571e-03 | rs115016376 | 3876 | 6 | 6 | 0.1578950 |   -1| 0.212256 | 1.017510 | 0.562631 | 0.00899101 | 0.01134860
NBPF3 | 164 | 1.037660 | 23.27200 | 11.7625 | 6.05282e-04 | rs12034222 | -3170 | 3 | 3 | 0.0789474 | 1 | 0.196096 | -2.429630 | 1.271050 | 0.01198800 | 0.01173110

Introduction of FastQTL (2015) 

1.ID of the tested molecular phenotype (in this particular case, the gene ID)
2.Number of variants tested in cis for this phenotype
3.MLE of the shape1 parameter of the Beta distribution
4.MLE of the shape2 parameter of the Beta distribution
5.Dummy [To be described later]
6.ID of the best variant found for this molecular phenotypes (i.e. with the smallest p-value)
7.Distance between the molecular phenotype - variant pair
8.The nominal p-value of association that quantifies how significant from 0, the regression coefficient is.
9.The slope associated with the nominal p-value of association [only in version > v2-184]
10.A first permutation p-value directly obtained from the permutations with the direct method. This is basically a corrected version of the nominal p-value that accounts for the fact that multiple variants are tested per molecular phenotype.
11.A second permutation p-value obtained via beta approximation. We advice to use this one in any downstream analysis.

**Comment by francois-a** [comment]
Hi,

Yes, the version in this repository was modified to include additional outputs, including allele frequencies. The column headers are added here: https://github.com/francois-a/fastqtl/blob/master/python/merge_chunks.py#L56

In case you haven't seen this yet, I recommend checking out [tensorQTL](https://github.com/broadinstitute/tensorqtl), which simplifies the mapping process (the calculations are exactly the same).

**Comment by boiscat** [comment]
Thanks for your answer and recommodation.
I have another quesition about cisQTL between phenotype start to end region .
I simply checked some of codes and found that the permutation analysis seems like just used phenotype_start but without phenotype_end. I want to reconfirm this because I am intrested in  cisQTLs inside the phenotype region.

**Comment by francois-a** [comment]
The phenotype start and end positions correspond to the transcription start site (end = start + 1, following BED conventions). The window around the TSS is set with `--window`.
