### ISSUE TITLE
Utilizing dosage input to encode a non-genetic 'genotype'

### ISSUE THREAD

**Issue by vkp3** [francois-a/fastqtl#14]
Hello,

I'm attempting to replicate the gtex-pipeline using scripts from the gtex-pipeline repository on GitHub.

However, my use case is a bit different than eQTL mapping. I would like to run a phenotype-QTL mapping, where: instead of many single-variant association tests, I want to test a general phenotype and its association to expression of many genes amongst tissues.

Most importantly, I would like to achieve fast performance on permutation testing for computing p-values of such a phenotype and its association with gene expression (across genes).

My intuition is to encode the phenotype as a dosage for a single genetic variant, across individuals, but I am unsure if this is supported by FastQTL and/or TensorQTL.

So, I'm wondering if this could be possible? If so, could you help me encode this strategy for FastQTL or TensorQTL? I would like to utilize the programs' fast performance in terms of permutation testing.

Thank you

**Comment by francois-a** [comment]
Please see https://github.com/broadinstitute/tensorqtl/issues/19. A similar strategy/coding is possible with FastQTL.
