### ISSUE TITLE
MAF could be the REF clarification

### ISSUE THREAD

**Issue by biostair** [francois-a/fastqtl#16]
This will look the same clarification that I asked about via the tensorQTL [https://github.com/broadinstitute/tensorqtl/issues/38]!!
 But this time I came via the GTEX pipeline documentation page that mentions FastQTL being used.

 To triple check, in FastQTL as well as tensorQTL, if the REF is not the major allele in certain cases, then it is reported as the MAF value.

Thanks (again)

**Comment by francois-a** [comment]
Hi, yes, thats correct. The output is exactly the same in FastQTL and tensorQTL.

**Comment by biostair** [comment]
I thought that would be the case. Thanks!
