### ISSUE TITLE
interaction term

### ISSUE THREAD

**Issue by montenegrina** [francois-a/fastqtl#17]
Hello,

To identify potential disease risk eQTLs, we planned to test for an interaction (eQTL x diabetes) term between genotype and diabetes status using the “modelLINEAR_CROSS” argument in MatrixEQTL. But we're wondering if the same type of analysis can be done with FastQTL. Can you please advise?

Cheers,
Ana

**Comment by francois-a** [comment]
Hi,
While this is possible with fastQTL, please take a look at [tensorQTL](https://github.com/broadinstitute/tensorqtl), which better supports interaction models.

**Comment by montenegrina** [comment]
Thank you!
