### ISSUE TITLE
Issue in FastQTL output

### ISSUE THREAD

**Issue by alvingao90** [francois-a/fastqtl#18]
Hi
When I used the nominal pass to call sQTLs, I found that there were a lot of repeat sQTLs in the output file named XXX.nominal.XX (example in the below). Can you give me some ideas about this issue?

23:28550049:28588575:clu_28643_NA 23_27774751_A_G -775299 0.0149343 -0.324037
23:28550049:28588575:clu_28643_NA 23_27774805_G_A -775245 7.07646e-06 -0.526193
......
23:28550049:28588575:clu_28643_NA 23_27774751_A_G -775299 0.0149343 -0.324037
23:28550049:28588575:clu_28643_NA 23_27774805_G_A -775245 7.07646e-06 -0.526193
......
23:28550049:28588575:clu_28643_NA 23_27774751_A_G -775299 0.0149343 -0.324037
23:28550049:28588575:clu_28643_NA 23_27774805_G_A -775245 7.07646e-06 -0.526193

Hui

**Comment by francois-a** [comment]
Hi, I believe this is an issue with chunks and how FastQTL parses the input files, but thought this only happens rarely (and is easy to filter from the results). I no longer maintain this version of FastQTL -- please take a look at [tensorQTL](https://github.com/broadinstitute/tensorqtl), which solves this problem.

**Comment by guanlingcattle** [comment]
Thanks for your quick reply.
