### ISSUE TITLE
cannot find FastQTL in sourceforge.net

### ISSUE THREAD

**Issue by ZunpengLiu** [francois-a/fastqtl#28]
Hi,

Thanks for developing this robust tool. I am trying to download this tool, but I can not find it in https://sourceforge.net/.  I want to make sure if you have delete it?

Thanks,

Zunpeng

**Comment by francois-a** [comment]
I'm not the original developer of FastQTL, but the version from this repository is identical to the original (which indeed no longer seems available) aside from some small improvements. You may want to check out [QTLtools](https://qtltools.github.io/qtltools/) (from the original FastQTL developers) or [TensorQTL](https://github.com/broadinstitute/tensorqtl) instead; both packages are functionally equivalent QTL mappers.
