### ISSUE TITLE
Error when trying to install FastQTL

### ISSUE THREAD

**Issue by ningbioinfo** [francois-a/fastqtl#3]
Hi,
I've tried to install FastQTL in either my local machine (MacOS) or my VM (ubuntu)

I've installed the required libraries in both system but when trying to install FastQTL by `make`, they encountered the same errors:

in MacOS:

```
$ make
g++ -std=c++11 -O3 -D_FAST_CORRELATION -Wall -Wextra -Wno-sign-compare -o obj/readInteractions.o -c src/readInteractions.cpp -Isrc -Ilib/Tabix -Ilib/Eigen -I../../R-3.2.4/src/include/
error: unable to open output file 'obj/readInteractions.o': 'No such file or directory'
1 error generated.
make: *** [obj/readInteractions.o] Error 1
```

in Ubuntu:

```
Assembler messages:
Fatal error: can't create obj/readThresholds.o: No such file or directory
Makefile:73: recipe for target 'obj/readThresholds.o' failed
make: *** [obj/readThresholds.o] Error 1
```

**Comment by francois-a** [comment]
The 'obj' directory was missing. I've updated the makefile to generate this.

**Comment by ningbioinfo** [comment]
Thanks for the update Francois.
I have another question:

fastqtl is successfully installed and I tried to use the python script `run_FastQTL_threaded.py` to do a eqtl mapping.
However, my vcf file is a merged vcf containing 60 samples so it has some genotyping like 1/2, 2/2, 3/3 and etc, which are not expected by fastqtl, do you have any suggestion on this?
