### ISSUE TITLE
how to convert vcf4.2 to vcf4.1?

### ISSUE THREAD

**Issue by jingydz** [francois-a/fastqtl#30]
$ /xxx/software/fastqtl/python/run_FastQTL_threaded.py --help
positional arguments:
  vcf                   Genotypes in VCF 4.1 format
  bed                   Phenotypes in UCSC BED extended format
  prefix                Prefix for output file name

Hi, I find my vcf file format is ##fileformat=VCFv4.2, but the fastQTL need the vcf4.1. 
How can I convert the vcf4.2 to vcf4.1?

Thanks in advance.

**Comment by francois-a** [comment]
There should be no need to convert from 4.2 to 4.1. Please consider using [tensorQTL](https://github.com/broadinstitute/tensorqtl) instead.
