### ISSUE TITLE
about map-full

### ISSUE THREAD

**Issue by feifeiflysky** [francois-a/fastqtl#34]
hi ,
Why am I only getting the top associations when using the --map-full option? I expected to see all the association results.
the code is as follows:
fastQTL --vcf SNP_SV${PBS_ARRAYID}ok.vcf.gz --bed t8.txt.gz --cov cov2.txt.gz --permute 100 --map-full --region chr1 --out map_full_fastqtl1.txt.gz.

looking forward to your reply.

**Comment by francois-a** [comment]
I'm no longer supporting FastQTL, please use [TensorQTL](https://github.com/broadinstitute/tensorqtl) instead. It has the same functionalities.
