### ISSUE TITLE
multi-alleles VCF

### ISSUE THREAD

**Issue by lyd0527** [francois-a/fastqtl#5]
Hi, 

Does FastQTL support multi-alleles VCF for input file such as CNV? Besides, How do I caculate the DS value? Thank you~

Best,

Yuanda

**Comment by francois-a** [comment]
Multi-allelic sites need to be split into pairs of biallelic representations. DS is calculated automatically from the GT field if that is present.

**Comment by lyd0527** [comment]
If we split the multi-alleles to the biallelic pair, each pair will have many missing value.  Do you know if some software such as matrix_eQTL support multi-alleles input ? Thank you.

**Comment by francois-a** [comment]
I'm not aware of existing QTL mappers that handle multi-allelic sites. FastQTL will impute the missing samples for these sites to the mean.
