### ISSUE TITLE
issue running fastqtl.static

### ISSUE THREAD

**Issue by bsun0802** [francois-a/fastqtl#6]
Hi, 

When I was trying to run `fastqtl.static`, it reports this error message.

`
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::logic_error> >'
  what():  character conversion failed
Aborted (core dumped)
`

That's the only error message, it does not show which line throw the error.

Do you have idea on solving this? I could run the original FastQTL.

**Comment by francois-a** [comment]
I've updated the static binary, so please try this again. The problem was due to incompatible boost versions.

Please also take a look at [tensorQTL](https://github.com/broadinstitute/tensorqtl) since I won't make further improvements to FastQTL.

**Comment by bsun0802** [comment]
Thank you so much. It has been fixed. 

I'll take a look at tensorQTL as well. Thanks for your work. 

And if you don't mind may I ask a question? In eQTL studies usually we do a rank-based normal transform, and then apply OLS fit. Since tensorQTL will be that fast on GPU, do you think it would be possible to change the linear model from OLS to robust models, thence do not perform this rank-based normal transform since it may cause loss of information.
