### ISSUE TITLE
An error occurred when I run the script run_fastqtl_threaded.py

### ISSUE THREAD

**Issue by stivenming** [francois-a/fastqtl#9]
**I downloaded your repo. 
And this is my command :**
 `python run_FastQTL_threaded.py 
prepare_expression/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_866Indiv.vcf.gz prepare_expression/Adipose_Subcutaneous_581_samples__prepare.expression.bed.gz Adipose_Subcutaneous 
--covariates covariate/Adipose_Subcutaneous_581_samples.PEER_covariates.txt 
--window 1e6 
--chunks 100 
--threads 30`
**Then , a error occurred , this is the whole output information:**
[Dec 04 19:17:29] Running FastQTL on 30 threads.
Processing chunk 1
Processing chunk 2
Processing chunk 3
Processing chunk 4
Processing chunk 5
Processing chunk 6
Processing chunk 7
Processing chunk 8
Processing chunk 10
Processing chunk 9
Processing chunk 12
Processing chunk 11
Processing chunk 13
Processing chunk 16
Processing chunk 14
Processing chunk 15
Processing chunk 17
Processing chunk 18
Processing chunk 19
Processing chunk 20
Processing chunk 21
Processing chunk 22
Processing chunk 23
Processing chunk 26
Processing chunk 24
Processing chunk 25
Processing chunk 27
Processing chunk 28
Processing chunk 29
Processing chunk 30
Processing chunk 31
Processing chunk 33
Processing chunk 32
Processing chunk 34
Processing chunk 35
Processing chunk 36
Processing chunk 37
Processing chunk 38
Processing chunk 39
Processing chunk 40
Processing chunk 41
Processing chunk 42
Processing chunk 43
Processing chunk 44
Processing chunk 45
Processing chunk 46
Processing chunk 49
Processing chunk 47
Processing chunk 48
Processing chunk 50
Processing chunk 51
Processing chunk 52
Processing chunk 53
Processing chunk 54
Processing chunk 55
Processing chunk 56
Processing chunk 57
Processing chunk 58
Processing chunk 61
Processing chunk 60
Processing chunk 59
Processing chunk 62
Processing chunk 63
Processing chunk 64
Processing chunk 65
Processing chunk 66
Processing chunk 67
Processing chunk 68
Processing chunk 69
Processing chunk 70
Processing chunk 73
Processing chunk 71
Processing chunk 72
Processing chunk 74
Processing chunk 75
Processing chunk 76
Processing chunk 77
Processing chunk 80
Processing chunk 78
Processing chunk 79
Processing chunk 81
Processing chunk 82
Processing chunk 83
Processing chunk 84
Processing chunk 85
Processing chunk 86
Processing chunk 87
Processing chunk 88
Processing chunk 89
Processing chunk 90
Processing chunk 91
Processing chunk 92
Processing chunk 93
Processing chunk 94
Processing chunk 95
Processing chunk 96
Processing chunk 97
Processing chunk 98
Processing chunk 99
Processing chunk 100
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/picb/lilab2/anaconda3_1/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/picb/lilab2/anaconda3_1/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/picb/lilab3/wangzengming/fastqtl-master/python/run_FastQTL_threaded.py", line 54, in perm_worker
    s = subprocess.check_call(cmd, shell=True, executable='/bin/bash', stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/picb/lilab2/anaconda3_1/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/picb/lilab3/wangzengming/fastqtl-master/bin/fastQTL --vcf prepare_expression/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_866Indiv.vcf.gz --bed prepare_expression/Adipose_Subcutaneous_581_samples__prepare.expression.bed.gz --window 1e6 --maf-threshold 0.0 --ma-sample-threshold 0 --interaction-maf-threshold 0 --cov covariate/Adipose_Subcutaneous_581_samples.PEER_covariates.txt --chunk 1 100 --out Adipose_Subcutaneous_chunk001.txt.gz --log Adipose_Subcutaneous_chunk001.log' returned non-zero exit status 127.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/picb/lilab3/wangzengming/fastqtl-master/python/run_FastQTL_threaded.py", line 95, in <module>
    assert res.get()[0]==0
  File "/picb/lilab2/anaconda3_1/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
subprocess.CalledProcessError: Command '/picb/lilab3/wangzengming/fastqtl-master/bin/fastQTL --vcf prepare_expression/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_866Indiv.vcf.gz --bed prepare_expression/Adipose_Subcutaneous_581_samples__prepare.expression.bed.gz --window 1e6 --maf-threshold 0.0 --ma-sample-threshold 0 --interaction-maf-threshold 0 --cov covariate/Adipose_Subcutaneous_581_samples.PEER_covariates.txt --chunk 1 100 --out Adipose_Subcutaneous_chunk001.txt.gz --log Adipose_Subcutaneous_chunk001.log' returned non-zero exit status 127.

**Comment by stivenming** [comment]
I fixed it by myself , thanks

**Comment by francois-a** [comment]
Can you please post the fix?

**Comment by stivenming** [comment]
**Actually , I caused the problem myself, and I solved it in two steps. 
First, I googled that "the exist status127" means "command not found" . So, I modified "fastqtl-master/bin/fastQTL.static" to "fastqtl-master/bin/fastQTL".
Then, Since I saw the usage of fastqtl at [https://github.com/broadinstitute/gtex-pipeline/tree/master/qtl](url) , covariates.txt is used there, and the correct usage requires covariates.txt.gz**
![image](https://user-images.githubusercontent.com/45038348/70222429-08908680-1785-11ea-81f1-b88c200e4f2c.png)

**Comment by hnaeem** [comment]
Dear, 

I'm calling permutation pass with Fastqtl, getting the following message:

**Any advise will be appreciated:**

Finished chunk 86
Finished chunk 97
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/gpfs/software/tools/python3.6.9/Python-3.6.9/install/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/gpfs/software/tools/python3.6.9/Python-3.6.9/install/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/gpfs/software/genomics/FastQTL/2.184/fastqtl/python/run_FastQTL_threaded.py", line 54, in perm_worker
    s = subprocess.check_call(cmd, shell=True, executable='/bin/bash', stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/gpfs/software/tools/python3.6.9/Python-3.6.9/install/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/gpfs/software/genomics/FastQTL/2.184/fastqtl/bin/fastQTL --vcf /gpfs/projects/SDR_transcriptomics_ymokrab/version_4/eQTL_analysis/eQTL_analysis/gene/fastqtl/base_seqbatch_totalReads_qbbbatch_rqn_WBC_BMI_peerFactors/eqtls_with_peer45/AFR/input/AFR.vcf.gz --bed /gpfs/projects/SDR_transcriptomics_ymokrab/version_4/eQTL_analysis/eQTL_analysis/gene/fastqtl/base_seqbatch_totalReads_qbbbatch_rqn_WBC_BMI_peerFactors/eqtls_with_peer45/AFR/input/gene_expression_inv_transform.bed.gz --window 1e6 --maf-threshold 0.0 --ma-sample-threshold 0 --interaction-maf-threshold 0 --cov /gpfs/projects/SDR_transcriptomics_ymokrab/version_4/eQTL_analysis/eQTL_analysis/gene/fastqtl/base_seqbatch_totalReads_qbbbatch_rqn_WBC_BMI_peerFactors/eqtls_with_peer45/AFR/input/covariates_peer45.txt.gz --permute 10 100 --chunk 3 100 --out AFR_chunk003.txt.gz --log AFR_chunk003.log' died with <Signals.SIGABRT: 6>.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/software/genomics/FastQTL/2.184/fastqtl/python/run_FastQTL_threaded.py", line 95, in <module>
    assert res.get()[0]==0
  File "/gpfs/software/tools/python3.6.9/Python-3.6.9/install/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
subprocess.CalledProcessError: Command '/gpfs/software/genomics/FastQTL/2.184/fastqtl/bin/fastQTL --vcf /gpfs/projects/SDR_transcriptomics_ymokrab/version_4/eQTL_analysis/eQTL_analysis/gene/fastqtl/base_seqbatch_totalReads_qbbbatch_rqn_WBC_BMI_peerFactors/eqtls_with_peer45/AFR/input/AFR.vcf.gz --bed /gpfs/projects/SDR_transcriptomics_ymokrab/version_4/eQTL_analysis/eQTL_analysis/gene/fastqtl/base_seqbatch_totalReads_qbbbatch_rqn_WBC_BMI_peerFactors/eqtls_with_peer45/AFR/input/gene_expression_inv_transform.bed.gz --window 1e6 --maf-threshold 0.0 --ma-sample-threshold 0 --interaction-maf-threshold 0 --cov /gpfs/projects/SDR_transcriptomics_ymokrab/version_4/eQTL_analysis/eQTL_analysis/gene/fastqtl/base_seqbatch_totalReads_qbbbatch_rqn_WBC_BMI_peerFactors/eqtls_with_peer45/AFR/input/covariates_peer45.txt.gz --permute 10 100 --chunk 3 100 --out AFR_chunk003.txt.gz --log AFR_chunk003.log' died with <Signals.SIGABRT: 6>.
